[package]
name = "shopper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rimui = { path = "../rimui" }
realtime-drawing = { path="../realtime-drawing" }
glam = { version="*", features=["serde"] }
miniquad = "0.3.0-alpha.30"
png = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
nfd2 = "*"
anyhow = "*"
log = "*"
directories = "*"